const cur=()=>{try{return JSON.parse(sessionStorage.getItem('sa_u')||localStorage.getItem('sa_u'))}catch(e){return null}};
const toast=m=>{const t=$('#toast');t.textContent=m;t.style.display='block';clearTimeout(t._);t._=setTimeout(()=>t.style.display='none',2800)};
const modal=h=>{const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="card" role="dialog">${h}<p><button class="btn o" id="mc">Close</button></p></div>`;document.body.append(m);m.querySelector('#mc').onclick=()=>m.remove();return m};
const pct=o=>o>=75?'Good':o>=65?'Warning':'Critical';
const bars=(o)=>Object.entries(o).map(([k,v])=>`<div style="margin:6px 0"><small>${k} — ${v}%</small><div class="bar"><i style="width:${v}%"></i></div></div>`).join('');
const tbl=(h,rows)=>`<div class="tw"><table><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${h.length}">No records yet.</td></tr>`}</table></div>`;
const pill=x=>`<span class="pill ${x.split(' ')[0]}">${x}</span>`;
const NAV={student:[['dash','Dashboard'],['scan','Scan QR'],['hist','History'],['prof','Profile'],['set','Settings']],faculty:[['dash','Dashboard'],['qr','Attendance'],['man','Manual Attendance'],['hist','History'],['rep','Reports'],['sec','Security'],['set','Settings']],admin:[['dash','Dashboard'],['usr','Students'],['usr','Faculty'],['hist','Attendance'],['rep','Reports'],['sec','Security'],['set','Settings']]};
let tm=[],stream=null;const clr=()=>{tm.forEach(clearInterval);tm=[];if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}};
function route(){clr();const u=cur(),h=location.hash.slice(1)||'home',[pg,pp]=h.split('/');
 if(h==='home'||h==='')return $('#root').innerHTML=landing();
 if(h==='login')return loginView();
 if(h==='signup')return signupView();
 if(!u){location.hash='login';return}
 const ok=NAV[u.role].some(n=>n[0]===pg);if(!ok){toast('Access denied for your role');location.hash='dash';return}
 const nav=NAV[u.role].map(n=>`<a href="#${n[0]}" class="${n[0]===pg?'on':''}">${n[1]}</a>`).join('')+`<a id="lo">Logout</a>`;
 $('#root').innerHTML=`<div class="app"><nav class="side"><h3>🎓 SmartAttend</h3><small style="color:var(--mu)">${u.role.toUpperCase()}</small>${nav}</nav><main class="main"><div class="row" style="justify-content:space-between"><h2>${u.name}</h2><button class="btn o s" onclick="theme()">🌓 Theme</button></div><div id="pg"></div></main></div>`;
 $('#lo').onclick=()=>{sessionStorage.removeItem('sa_u');localStorage.removeItem('sa_u');location.hash='home'};
 const V={student:{dash:sDash,scan:sScan,hist:hist,prof:prof,set:setg},faculty:{dash:fDash,qr:fQR,man:man,hist:hist,rep:rep,sec:sec,set:setg},admin:{dash:aDash,usr:usr,hist:hist,rep:rep,sec:sec,set:setg}}[u.role];V[pg](u,$('#pg'))}
function theme(){const d=document.documentElement,dk=getComputedStyle(d).getPropertyValue('--bg').trim()==='#0f1226';d.dataset.theme=dk?'light':'dark'}
function landing(){const f=['🔄 Dynamic QR Attendance','🛡️ Anti-Proxy Detection','📝 Manual Attendance','📊 Real-Time Analytics','🔐 Secure Authentication','📄 Attendance Reports'];
 return`<div class="top"><b>🎓 SmartAttend</b><a href="#login">Login</a></div><section class="hero"><h1>SmartAttend</h1><h2>Secure Attendance. Prevent Proxy. Track Smarter.</h2><p>An intelligent attendance management system combining manual attendance, dynamic QR verification and anti-proxy security.</p><div class="row" style="justify-content:center"><a href="#signup"><button class="btn" style="background:#fff;color:#4f46e5">Get Started</button></a><a href="#login"><button class="btn o" style="color:#fff;border-color:#fff">Login</button></a><a href="#login/demo"><button class="btn o" style="color:#fff;border-color:#fff">View Demo</button></a></div></section>
 <div class="wrap"><div class="grid">${f.map(x=>`<div class="card"><b>${x}</b></div>`).join('')}</div><h2 style="margin-top:30px">Why SmartAttend?</h2><div class="grid"><div class="card"><h3 class="er">Traditional attendance</h3>• Time consuming<br>• Manual errors<br>• Proxy attendance<br>• Difficult record management</div><div class="card"><h3 class="ok">SmartAttend</h3>• Fast attendance<br>• Dynamic QR<br>• Security verification<br>• Automated reports<br>• Suspicious activity detection</div></div></div>`}
function loginView(){const demo=location.hash.includes('demo');
 $('#root').innerHTML=`<div class="wrap" style="max-width:420px"><a href="#home">← Home</a><div class="card" style="margin-top:12px"><h2>🎓 Sign in</h2><form id="lf"><label for="id">Email / Student ID</label><input id="id" required autocomplete="username"><label for="pw">Password</label><div class="row" style="flex-wrap:nowrap"><input id="pw" type="password" required minlength="6" autocomplete="current-password"><button type="button" class="btn o s" id="sp">Show</button></div><label for="rl">Role</label><select id="rl"><option value="student">Student</option><option value="faculty">Faculty</option><option value="admin">Admin</option></select><label><input type="checkbox" id="rm" style="width:auto"> Remember me</label><p><button class="btn" style="width:100%">Login</button></p><a href="#" id="fp">Forgot password?</a> · <a href="#signup">Create an account</a></form>
 <p style="font-size:13px;color:var(--mu)"><b>Demo accounts</b> (click to fill):<br><a href="#" data-d="rahul@college.edu|student123|student">Student: Rahul</a> · <a href="#" data-d="sharma@college.edu|faculty123|faculty">Faculty: Prof. Sharma</a> · <a href="#" data-d="admin@college.edu|admin123|admin">Admin</a></p></div></div>`;
 $('#sp').onclick=e=>{const p=$('#pw');p.type=p.type=='password'?'text':'password';e.target.textContent=p.type=='password'?'Show':'Hide'};
 document.querySelectorAll('[data-d]').forEach(a=>a.onclick=e=>{e.preventDefault();const[i,p,r]=a.dataset.d.split('|');$('#id').value=i;$('#pw').value=p;$('#rl').value=r});
 $('#fp').onclick=e=>{e.preventDefault();toast('Demo: password reset email would be sent by backend')};
 if(demo)$('[data-d]').click();
 $('#lf').onsubmit=async e=>{e.preventDefault();try{const u=await API.login($('#id').value.trim(),$('#pw').value,$('#rl').value);const s=JSON.stringify(u);(($('#rm').checked)?localStorage:sessionStorage).setItem('sa_u',s);location.hash='dash'}catch(x){toast(x.message)}}}
function signupView(){
 $('#root').innerHTML=`<div class="wrap" style="max-width:460px"><a href="#home">← Home</a><div class="card" style="margin-top:12px"><h2>🎓 Create account</h2><form id="sf"><label for="sn">Full name</label><input id="sn" required minlength="3"><label for="se">Email</label><input id="se" type="email" required autocomplete="email"><label for="sr">Role</label><select id="sr"><option value="student">Student</option><option value="faculty">Faculty</option></select><div id="stu"><label for="sid">Roll number</label><input id="sid" pattern="[0-9A-Za-z-]{2,12}" title="2-12 letters/numbers"><div class="grid"><div><label for="sy">Year</label><select id="sy"><option>FY</option><option selected>SY</option><option>TY</option><option>BE</option></select></div><div><label for="sv">Division</label><input id="sv" value="A" maxlength="2"></div></div></div><label for="sd">Department</label><input id="sd" value="CSE" required><label for="sp1">Password (min 8 chars, with a number)</label><input id="sp1" type="password" required minlength="8" autocomplete="new-password"><label for="sp2">Confirm password</label><input id="sp2" type="password" required autocomplete="new-password"><p><button class="btn" style="width:100%">Sign up</button></p><small style="color:var(--mu)">Admin accounts are created by an administrator only. Passwords are hashed (SHA-256 in this demo; use bcrypt on a real backend).</small><p>Already registered? <a href="#login">Login</a></p></form></div></div>`;
 $('#sr').onchange=()=>$('#stu').style.display=$('#sr').value==='student'?'':'none';
 $('#sf').onsubmit=async e=>{e.preventDefault();load();const r=$('#sr').value,em=$('#se').value.trim().toLowerCase(),p=$('#sp1').value,sid=$('#sid').value.trim();
  if(p!==$('#sp2').value)return toast('Passwords do not match');if(!/\d/.test(p))return toast('Password needs at least one number');
  if(r==='student'&&!sid)return toast('Roll number is required for students');
  if(DB.users.some(x=>x.email.toLowerCase()===em||(r==='student'&&x.sid===sid)))return toast('Email or roll number already registered');
  DB.users.push({id:Date.now(),name:$('#sn').value.trim(),email:em,hash:await sha(p),role:r,sid:r==='student'?sid:'',dept:$('#sd').value.trim(),year:r==='student'?$('#sy').value:'',div:r==='student'?$('#sv').value.trim():'',status:'Active'});
  save();toast('Account created — please log in');location.hash='login'}}
function sDash(u,el){load();const mine=DB.att.filter(a=>a.sid===u.sid),tot=mine.length,pr=mine.filter(a=>a.status!=='Absent').length,ov=tot?Math.round(pr/tot*100):0,td=mine.filter(a=>new Date(a.ts).toDateString()===new Date().toDateString());
 const sp={};Object.keys(SUBJ).forEach(s=>{const m=mine.filter(a=>a.sub===s);sp[s]=m.length?Math.round(m.filter(a=>a.status!=='Absent').length/m.length*100):0});
 el.innerHTML=`${tot&&ov<75?'<div class="card er">⚠️ Low Attendance — Your attendance is below the required 75%.</div>':''}<p>Roll ${u.sid} · ${u.dept} · ${u.year}-${u.div}</p><div class="grid"><div class="card stat"><span>Overall Attendance</span><b>${tot?ov+'% '+pill(pct(ov)):'—'}</b></div><div class="card stat"><span>Total classes</span><b>${tot}</b></div><div class="card stat"><span>Present</span><b>${pr}</b></div><div class="card stat"><span>Absent</span><b>${tot-pr}</b></div></div>
 <div class="grid" style="margin-top:14px"><div class="card"><h3>Subject-wise</h3>${tot?bars(sp):'No attendance recorded yet.'}</div><div class="card"><h3>Today's Attendance</h3>${tbl(['Subject','Time','Status'],td.map(a=>[a.sub,fmt(a.ts),pill(a.status)]))}<p><a href="#scan"><button class="btn">Scan Attendance QR</button></a></p></div></div>`}
function sScan(u,el){el.innerHTML=`<div class="card"><h2>Scan Attendance QR</h2><div class="qrbox"><video id="v" playsinline muted></video><canvas id="cv" hidden></canvas><div class="row"><button class="btn" id="cam">Start camera</button><button class="btn o" id="sl">Demo: scan live QR</button><button class="btn o" id="so">Demo: scan old/shared QR</button><label class="btn o" style="cursor:pointer">Upload QR photo<input type="file" id="fi" accept="image/*" hidden></label></div><small style="color:var(--mu)">Demo buttons simulate scanning when you have no camera: the live QR from the open faculty session, or an old screenshot.</small><div id="res"></div></div></div>`;
 const show=r=>{$('#res').innerHTML=r.ok?`<h3 class="ok">Attendance Successful ✅</h3><p>${r.r.name}<br>${r.r.sub} · ${new Date(r.r.ts).toLocaleDateString()} ${fmt(r.r.ts)}<br>Method: QR · Verification: Successful</p>`:`<h3 class="er">${r.title||'Failed'}</h3><p>${r.msg}</p>`;load()};
 const load=()=>DB=JSON.parse(localStorage.getItem('sa_db'));const go=raw=>{load();show(API.scan(u,raw))};
 const pick=old=>{load();const s=DB.session;if(!s)return go(JSON.stringify({s:'x',t:'x'}));const t=old?s.tokens[0]:s.tokens[s.tokens.length-1];if(old&&s.tokens.length<2)return toast('Wait for the QR to rotate once, then try old QR');go(JSON.stringify({s:s.id,t:t.token}))};
 $('#fi').onchange=e=>{const f=e.target.files[0];if(!f)return;if(typeof jsQR==='undefined')return toast('QR decoder failed to load');const fr=new FileReader();fr.onload=()=>{const im=new Image();im.onload=()=>{const c=$('#cv'),x=c.getContext('2d');c.width=im.width;c.height=im.height;x.drawImage(im,0,0);const q=jsQR(x.getImageData(0,0,c.width,c.height).data,c.width,c.height);q?go(q.data):toast('No QR found in that image')};im.src=fr.result};fr.readAsDataURL(f)};
 $('#sl').onclick=()=>pick(0);$('#so').onclick=()=>pick(1);
 $('#cam').onclick=async()=>{if(typeof jsQR==='undefined')return toast('QR decoder failed to load');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});const v=$('#v');v.srcObject=stream;v.play();const c=$('#cv'),x=c.getContext('2d');
  tm.push(setInterval(()=>{if(!v.videoWidth)return;c.width=v.videoWidth;c.height=v.videoHeight;x.drawImage(v,0,0);const q=jsQR(x.getImageData(0,0,c.width,c.height).data,c.width,c.height);if(q){go(q.data);clr()}},400))}catch(e){toast('Camera blocked ('+e.name+') — use Upload QR photo or the demo buttons')}}}
function fDash(u,el){load();const att=DB.att.filter(a=>a.method==='QR'||1),pr=att.filter(a=>a.status==='Present').length;
 el.innerHTML=`<div class="grid"><div class="card stat"><span>Today's Classes</span><b>6</b></div><div class="card stat"><span>Students Present</span><b>142</b></div><div class="card stat"><span>Absent</span><b>28</b></div><div class="card stat"><span>Suspicious Attempts</span><b>${7+DB.events.length-3}</b></div></div>
 <div class="card" style="margin-top:14px"><h3>Start Attendance</h3><div class="grid"><div><label>Subject</label><select id="sb">${Object.keys(SUBJ).map(s=>`<option>${s}</option>`).join('')}</select></div><div><label>Class</label><input id="cl" value="SY-CSE"></div><div><label>Division</label><input id="dv" value="A"></div><div><label>Date / Start</label><input value="${new Date().toLocaleDateString()} ${fmt(now())}" readonly></div></div><p class="row"><button class="btn" id="gq">Generate Dynamic QR</button><a href="#man"><button class="btn o">Manual Attendance</button></a></p></div>`;
 $('#gq').onclick=()=>{load();API.start({sub:$('#sb').value,cls:$('#cl').value.trim(),div:$('#dv').value.trim(),fac:u.name});location.hash='qr'}}
function load(){DB=JSON.parse(localStorage.getItem('sa_db'))}
function fQR(u,el){load();el.innerHTML=`<div class="card"><div class="qrbox" id="qb"></div></div><div class="card" style="margin-top:14px"><h3>Live attendance</h3><div id="lv"></div></div>`;let last='';
 const draw=()=>{load();API.tick();load();const s=DB.session,b=$('#qb');if(!b)return;
  if(!s){last='';b.innerHTML=`<h3>${DB.hist.length?'Attendance Session Expired':'No active session'}</h3><button class="btn" id="ns">Start Attendance (DSA · SY-CSE)</button>`;$('#ns').onclick=()=>{API.start({sub:'DSA',cls:'SY-CSE',div:'A',fac:u.name});load();draw()};return}
  const c=s.tokens[s.tokens.length-1],left=Math.max(0,Math.ceil((s.end-now())/1000));
  if(!$('#qr')||last!==c.token){b.innerHTML=`<b>${s.sub} · ${s.cls}-${s.div} · ${s.fac} · ${new Date().toDateString()}</b><div id="qr"></div><div class="t" id="tt"></div><div id="up" class="ok"></div><small>Token ${s.tokens.length} · rotates every 7–9s · session ends at 45s</small>`;
   try{new QRCode($('#qr'),{text:JSON.stringify({s:s.id,t:c.token}),width:260,height:260})}catch(e){$('#qr').innerHTML='<small>QR library failed to load (check internet). Payload:<br>'+JSON.stringify({s:s.id,t:c.token})+'</small>'}if(last)$('#up').textContent='QR Updated 🔄';last=c.token}
  $('#tt').textContent=left+'s';
  const l=DB.att.filter(a=>a.sess===s.id);$('#lv').innerHTML=tbl(['Student','Time','Method'],l.map(a=>[a.name,fmt(a.ts),'QR ✅']))};
 draw();tm.push(setInterval(draw,500))}
function man(u,el){load();const L=DB.users.filter(x=>x.role==='student'&&x.status==='Active').map(x=>[x.sid,x.name]);const log=JSON.parse(localStorage.getItem('sa_mlog')||'[]');
 el.innerHTML=`<div class="card"><h3>Manual Attendance — DSA</h3>${tbl(['Roll No','Student','Status','Action'],L.map((r,i)=>[r[0],r[1],`<span id="p${i}">${pill('Present')}</span>`,`<select data-r="${i}" aria-label="Status ${r[1]}"><option>Present</option><option>Absent</option><option>Late</option></select>`]))}<p><button class="btn" id="sv">Save Attendance</button></p><small>${log.length?'Last saved by '+log[0]:'No edits recorded yet'}</small></div>`;
 el.querySelectorAll('select').forEach(s=>s.onchange=()=>$('#p'+s.dataset.r).innerHTML=pill(s.value));
 $('#sv').onclick=()=>{load();el.querySelectorAll('select').forEach(s=>{const r=L[s.dataset.r];DB.att.push({sid:r[0],name:r[1],sub:'DSA',ts:now(),status:s.value,method:'Manual',ver:'By '+u.name})});save();log.unshift(`${u.name} at ${new Date().toLocaleString()}`);localStorage.setItem('sa_mlog',JSON.stringify(log));toast('Attendance saved (audit logged)');man(u,el)}}
function hist(u,el){load();let a=[...DB.att].sort((x,y)=>y.ts-x.ts);if(u.role==='student')a=a.filter(x=>x.sid===u.sid);
 el.innerHTML=`<div class="card"><h3>Attendance History</h3><div class="grid"><div><label>Subject</label><select id="fs"><option value="">All</option>${Object.keys(SUBJ).map(s=>`<option>${s}</option>`).join('')}</select></div><div><label>Method</label><select id="fm"><option value="">All</option><option>QR</option><option>Manual</option></select></div><div><label>Date</label><input type="date" id="fd"></div><div><label>Student</label><input id="fn" placeholder="name or roll"></div></div><div id="ht"></div></div>`;
 const f=()=>{const s=$('#fs').value,m=$('#fm').value,d=$('#fd').value,n=$('#fn').value.toLowerCase();
  const r=a.filter(x=>(!s||x.sub===s)&&(!m||x.method===m)&&(!d||new Date(x.ts).toISOString().slice(0,10)===d)&&(!n||(x.name+x.sid).toLowerCase().includes(n)));
  $('#ht').innerHTML=tbl(['Student','Subject','Date','Time','Status','Method','Verification'],r.map(x=>[x.name,x.sub,new Date(x.ts).toLocaleDateString(),fmt(x.ts),pill(x.status),x.method,x.ver]))};
 el.querySelectorAll('select,input').forEach(i=>i.oninput=f);f()}
function sec(u,el){load();const E=DB.events.slice().sort((a,b)=>b.ts-a.ts),n=t=>E.filter(e=>e.type.includes(t)).length;
 el.innerHTML=`<div class="grid"><div class="card stat"><span>Suspicious Attempts</span><b>${E.length+15}</b></div><div class="card stat"><span>Expired QR Attempts</span><b>${n('Expired')+8}</b></div><div class="card stat"><span>Multiple Login Attempts</span><b>${n('Multiple')+4}</b></div><div class="card stat"><span>Location Failures</span><b>${n('Location')+3}</b></div></div>
 <div class="card" style="margin-top:14px"><h3>Security events</h3><p style="color:var(--mu);font-size:13px">Signals are for faculty review — a single event never proves cheating, and no method makes proxying impossible.</p>${tbl(['Student','Event','Time','Risk','Action'],E.map(e=>[e.sid,e.type,fmt(e.ts),pill(e.risk),e.rev?'Reviewed ✔':`<button class="btn s" data-v="${e.id}">View</button> <button class="btn s o" data-r="${e.id}">Mark Reviewed</button> <button class="btn s d" data-b="${e.id}">Block Session</button>`]))}<p><button class="btn o" id="ex">Export Report</button></p></div>
 <div class="card" style="margin-top:14px"><h3>7 defence layers</h3>1 Rotating QR (7–9s) · 2 45s session · 3 Authenticated student · 4 Duplicate prevention · 5 Login/session tracking · 6 Optional classroom location check · 7 Suspicious-activity review</div>`;
 el.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{const e=E.find(x=>x.id===b.dataset.v);modal(`<h3>${e.type}</h3><p>Student: ${e.sid}<br>Time: ${new Date(e.ts).toLocaleString()}<br>Risk: ${e.risk}</p><p>Recommended: review in context with other signals before action.</p>`)});
 el.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{DB.events.find(x=>x.id===b.dataset.r).rev=1;save();sec(u,el)});
 el.querySelectorAll('[data-b]').forEach(b=>b.onclick=()=>{toast('Session blocked (demo) — user must re-authenticate')});
 $('#ex').onclick=()=>csv('suspicious',['student','event','time','risk'],E.map(e=>[e.sid,e.type,fmt(e.ts),e.risk]))}
function csv(n,h,r){const t=[h,...r].map(x=>x.map(c=>`"${c}"`).join(',')).join('\n');const m=modal(`<h3>${n}.csv</h3><textarea style="width:100%;height:200px">${t}</textarea><p><button class="btn s" id="cp">Copy CSV</button> <button class="btn s o" onclick="window.print()">Print</button></p>`);m.querySelector('#cp').onclick=()=>{m.querySelector('textarea').select();try{navigator.clipboard.writeText(t)}catch(e){document.execCommand('copy')}toast('Copied — paste into Excel/Sheets')}}
function rep(u,el){load();const T=['Daily attendance','Weekly attendance','Monthly attendance','Student attendance','Subject attendance','Defaulter list','Suspicious activity'];
 el.innerHTML=`<div class="card"><h3>Reports</h3><label>Report type</label><select id="rt">${T.map(t=>`<option>${t}</option>`).join('')}</select><div id="rb"></div><p class="row"><button class="btn" id="e1">Export CSV</button><button class="btn o" onclick="window.print()">Print Report</button></p></div>`;
 const data=()=>{const t=$('#rt').value;if(t==='Defaulter list')return[['Student','Subject','%'],[['Amit','OS',68],['Rohit','CN',61]]];if(t==='Suspicious activity')return[['Student','Event','Risk'],DB.events.map(e=>[e.sid,e.type,e.risk])];if(t==='Subject attendance')return[['Subject','%'],Object.entries(SUBJ)];return[['Student','Subject','Status','Method'],DB.att.slice(-30).map(a=>[a.name,a.sub,a.status,a.method])]};
 const f=()=>{const[h,r]=data();$('#rb').innerHTML=tbl(h,r)};$('#rt').onchange=f;f();$('#e1').onclick=()=>{const[h,r]=data();csv($('#rt').value.replace(/ /g,'_'),h,r)}}
function aDash(u,el){load();el.innerHTML=`<div class="grid"><div class="card stat"><span>Total Students</span><b>850</b></div><div class="card stat"><span>Total Faculty</span><b>42</b></div><div class="card stat"><span>Departments</span><b>6</b></div><div class="card stat"><span>Today's Attendance</span><b>91%</b></div><div class="card stat"><span>Suspicious Attempts</span><b>${DB.events.length+15}</b></div></div>
 <div class="grid" style="margin-top:14px"><div class="card"><h3>Weekly attendance</h3>${bars({Mon:92,Tue:90,Wed:88,Thu:91,Fri:85})}</div><div class="card"><h3>Department attendance</h3>${bars({CSE:91,IT:89,ENTC:86,MECH:82,CIVIL:84,AIDS:90})}</div><div class="card"><h3>Subject attendance</h3>${bars(SUBJ)}</div><div class="card"><h3>Monthly · Present vs Absent</h3>${bars({Jul:88,Aug:90,Sep:87,Oct:91})}<small>Present 91% · Absent 9% today</small></div></div>`}
function usr(u,el){load();const L=DB.users.filter(x=>x.role!=='admin');
 const draw=()=>{el.innerHTML=`<div class="card"><div class="row" style="justify-content:space-between"><h3>User Management</h3><button class="btn" id="ad">Add user</button></div>${tbl(['Name','Roll','Email','Role','Dept','Year','Div','Status','Actions'],DB.users.filter(x=>x.role!=='admin').map(x=>[x.name,x.sid||'—',x.email,x.role,x.dept,x.year,x.div,pill(x.status==='Active'?'Good':'Critical').replace('Good','Active').replace('Critical','Inactive'),`<button class="btn s o" data-t="${x.id}">${x.status==='Active'?'Deactivate':'Activate'}</button> <button class="btn s o" data-l="${x.id}">Logins</button> <button class="btn s o" data-p="${x.id}">Reset</button>`]))}</div>`;
  el.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{const x=DB.users.find(y=>y.id==b.dataset.t);x.status=x.status==='Active'?'Inactive':'Active';save();draw()});
  el.querySelectorAll('[data-l]').forEach(b=>b.onclick=()=>{const l=DB.logins.filter(x=>x.uid==b.dataset.l);modal('<h3>Login history</h3>'+(l.length?l.map(x=>new Date(x.t).toLocaleString()).join('<br>'):'No logins recorded yet.'))});
  el.querySelectorAll('[data-p]').forEach(b=>b.onclick=async()=>{const x=DB.users.find(y=>y.id==b.dataset.p);x.hash=await sha('reset123');save();toast('Password reset to temporary: reset123')});
  $('#ad').onclick=()=>{const m=modal(`<h3>Add user</h3><form id="af"><label>Name</label><input id="an" required><label>Email</label><input id="ae" type="email" required><label>Roll number (students)</label><input id="ar"><label>Role</label><select id="ro"><option>student</option><option>faculty</option></select><label>Department</label><input id="ad2" value="CSE"><label>Year</label><select id="ay"><option>FY</option><option selected>SY</option><option>TY</option><option>BE</option></select><label>Division</label><input id="av" value="A"><p><button class="btn">Save</button></p></form>`);
   m.querySelector('#af').onsubmit=async e=>{e.preventDefault();if(DB.users.some(x=>x.email===$('#ae').value))return toast('Email already exists');DB.users.push({id:Date.now(),name:$('#an').value,email:$('#ae').value,hash:await sha('welcome123'),role:$('#ro').value,sid:$('#ar').value,dept:$('#ad2').value,year:$('#ay').value,div:$('#av').value,status:'Active'});save();m.remove();toast('User added (password: welcome123)');draw()}}};draw()}
function prof(u,el){el.innerHTML=`<div class="card"><h3>Profile</h3>Name: ${u.name}<br>Roll: ${u.sid}<br>Email: ${u.email}<br>Department: ${u.dept} · ${u.year}-${u.div}</div>`}
function setg(u,el){el.innerHTML=`<div class="card"><h3>Settings</h3><button class="btn" onclick="theme()">Toggle light/dark</button> <button class="btn d" id="rs">Reset demo data</button></div>`;$('#rs').onclick=()=>{localStorage.removeItem('sa_db');location.reload()}}
addEventListener('hashchange',route);init().then(route);
